version: '3.8'
services:
  node:
    build:
      context: .
      args:
        - NODE_ENV=production
    env_file: .env
    ports:
      - '80:3000'
    volumes:
      - .:/opt/node_app/app
      - ./package.json:/opt/node_app/package.json
      - ./package-lock.json:/opt/node_app/package-lock.json
      - notused:/opt/node_app/app/node_modules
volumes:
  notused:
