version: '3.8'
services:
  node:
    build:
      context: .
      args:
        - NODE_ENV=development
    command: ../node_modules/.bin/nodemon --experimental-modules --es-module-specifier-resolution=node -L --inspect=0.0.0.0:9229 ./bin/www
    env_file: .env
    ports:
      - '3000:3000'
      - '9229:9229'
      - '9230:9230'
    volumes:
      - .:/opt/node_app/app
      - ./package.json:/opt/node_app/package.json
      - ./package-lock.json:/opt/node_app/package-lock.json
      - node-app_notused:/opt/node_app/app/node_modules

volumes:
  node-app_notused:
